### ISSUE TITLE
A widely used Cloudflare deployment appears inoperable

### ISSUE THREAD

**Issue by NVB9ALT** [tomphttp/bare-server-node#19] opened 2023-04-18 22:12 UTC
I've been trying to use both the "holyuboffical.net" and "hypertabs.cc" proxy services for about a week now, and neither seems to be able to connect to the server. "uv.holyuboffical.net", "rh.holyuboffical.net", and "uv.hypertabs.cc" all say that the server they're trying to access is down. I don't know what the structure is for these services, but the fact that two different services _and_ two different proxies are all inoperative due to a faulty server (according to the Cloudflare error page) suggests this is not an issue with the individual services.

Steps to reproduce:
- Enter a URL into "holyubofficial.net" or "hypertabs.cc" and observe the resulting error
- (Optional) Change the proxy used by "holyubofficial.net" in the settings, then repeat the above step
- (Optional) Enter "uv.holyuboffical.net", "rh.holyubofficial.net", or "uv.hypertabs.cc" into your search engine's search bar (Google, Firefox, Bing, etc.)

Screenshots available on request.

**Comment by CountBleck** [comment] 2023-04-18 22:20
That's not a bug with `bare-server-node`. It's likely just an issue with how they set up their reverse proxy. This isn't the right place to bring this issue up, and you should probably close this issue as "not planned". `bare-server-node` does indeed work. I already DMed the operator of those servers (who happens to be a maintainer of UV and Bare itself) and he doesn't appear to show interest in fixing that issue.

**Closed as not planned** 2023-04-19 14:59 UTC
